- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  pre_tasks:
    - name: Update cache
      apt:
        update_cache: true
      tags:
      - node
      - zsh
  tasks: 
    - include: ./tasks/anki.yml
    - include: ./tasks/discord.yml
    - include: ./tasks/node.yml
    - include: ./tasks/obsidian.yml
    - include: ./tasks/spotify.yml
    - include: ./tasks/ssh.yml
    - include: ./tasks/steam.yml
    - include: ./tasks/terminator.yml
    - include: ./tasks/vscode.yml
    - include: ./tasks/zsh.yml