- name: Install Node prerequisites
  become: true
  apt:
    name:
      - curl
    state: present
  tags:
    - node

- name: Install Node
  become: true
  apt:
    name: ['nodejs', 'npm']
  tags:
  - node

- name: Install Yarn
  npm: 
    name: yarn
    global: true
  tags:
  - node

- name: Install n (a node version manager)
  npm: 
    name: n
    global: true
  tags:
  - node

- name: Install Node version 16
  shell: n 16
  tags:
  - node