name: Ansible Daily Run

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v2
        with:
          version: "20.10.0" 

      - name: Build Docker image
        run: docker build -t ansible-playbook-runner .

      - name: Run Ansible playbook in Docker container
        run: docker run --rm ansible-playbook-runner
